server:
  port: 8080

spring:
  application:
    name: ONLINE-EDUCATION

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  banner:
    location: classpath:banner.txt

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_education
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    analytics-enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

education:
  app:
    file:
      base-folder: /home/abdulbosit/IdeaProjects/certificate/ONLINE-EDUCATION/src/main/resources/education/files/content
      icons: /home/abdulbosit/IdeaProjects/certificate/ONLINE-EDUCATION/src/main/resources/education/files/icons

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    uz:
      pdp:
        online_education:
          service:
            GenerateService=DEBUG:
#    root: WARN
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type.descriptor.sql: TRACE
#    com.example.your.app: DEBUG

recaptcha:
  site-key: ${RECAPTCHA_SITE_KEY}
  secret-key: ${RECAPTCHA_SECRET_KEY}

application:
  jwt:
    # BU JUDA MUHIM: Bu kalit production muhiti uchun mutlaqo o'zgartirilishi kerak!
    # U Base64 formatida kodlangan va yetarlicha uzun (kamida 256 bit) bo'lishi lozim.
    # Onlayn generatorlardan foydalanib, xavfsiz kalit yaratishingiz mumkin.
    # Masalan: `openssl rand -base64 32` buyrug'i yordamida.
    secret: ${JWT_SECRET_KEY}

    # Access tokenning yashash muddati.
    # Formatlar: 's' - soniya, 'm' - daqiqa, 'h' - soat, 'd' - kun.
    # Masalan: 15 daqiqa uchun '15m', 1 soat uchun '1h'.
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}

    # Refresh tokenning yashash muddati.
    # Bu odatda ancha uzoqroq bo'ladi, masalan 7 kun.
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

  minio:
    endpoint: ${MINION_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    buckets:
      - images
      - other
      - icons

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webhook-path: ${TELEGRAM_BOT_PATH}
    chat-id: ${TELEGRAM_CHAT_ID}
    channel-id: ${TELEGRAM_BOT_CHANNEL}