server:
  port: 8080

spring:
  application:
    name: ONLINE-EDUCATION

  banner:
    location: classpath:banner.txt

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:online-education;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 123

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

education:
  app:
    base-folder: C:\PDP\ONLINE-EDUCATION

springdoc:
  swagger-ui:
    path: /swagger-ui.html

recaptcha:
  site-key: ${RECAPTCHA_SITE_KEY}
  secret-key: ${RECAPTCHA_SECRET_KEY}

#logging:
#  level:
#    root: WARN
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type.descriptor.sql: TRACE
#    com.example.your.app: DEBUG
