server:
  port: 8080

spring:
  application:
    name: ONLINE-EDUCATION

  banner:
    location: classpath:banner.txt

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_education
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    analytics-enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

education:
  app:
    base-folder: /home/abdulbosit/IdeaProjects/certificate/ONLINE-EDUCATION

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    com.example.your.app: DEBUG

recaptcha:
  site-key: ${RECAPTCHA_SITE_KEY}
  secret-key: ${RECAPTCHA_SECRET_KEY}
