version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    command: server /data --console-address ":9000" --address ":9001"
    ports:
      - "9000:9000" # MinIO Console uchun
      - "9001:9001" # MinIO API uchun
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

volumes:
  minio-data: