package uz.pdp.online_education.telegram.enums;

public enum UserState {

    DEFAULT,
    AUTHENTICATED,
    UNREGISTERED,
    DASHBOARD,

    STUDENT_SUPPORT_SEND_MESSAGE,
    STUDENT_SUPPORT_MESSAGE_CONFIRMATION,



    ADMIN_MAIN_MENU,
    ADMIN_MANAGING_USERS,
    ADMIN_MANAGING_COURSES,
    ADMIN_PREPARING_BROADCAST,
    ADMIN_VIEWING_STATISTICS,

    STUDENT_MAIN_MENU,
    STUDENT_VIEWING_MY_COURSES,
    STUDENT_VIEWING_ALL_COURSES,
    STUDENT_MANAGING_BALANCE,
    STUDENT_AWAITING_SUPPORT_MESSAGE,

    AWAITING_BROADCAST_MESSAGE,
    ADMIN_AWAITING_USER_SEARCH_QUERY,
    ADMIN_VIEWING_SEARCH_RESULTS,
    ADMIN_AWAITING_COURSE_SEARCH_QUERY,


    NONE,

    AWAITING_COURSE_TITLE,
    AWAITING_COURSE_DESCRIPTION,
    AWAITING_COURSE_THUMBNAIL,
    AWAITING_COURSE_CATEGORY_CHOICE,
    AWAITING_COURSE_CONFIRMATION,

    AWAITING_MODULE_TITLE,
    AWAITING_MODULE_DESCRIPTION,
    AWAITING_MODULE_PRICE,
    AWAITING_MODULE_CONFIRMATION,

    AWAITING_LESSON_TITLE,
    AWAITING_LESSON_DESCRIPTION,
    AWAITING_LESSON_IS_FREE,
    AWAITING_LESSON_CONFIRMATION,

    AWAITING_CHOOSE_CONTENT,
    AWAITING_TEXT_CONTENT,
    AWAITING_ATTACHMENT_CONTENT,
    AWAITING_QUIZ_CONTENT,

    AWAITING_EDIT_COURSE_TITLE,
    AWAITING_EDIT_COURSE_DESCRIPTION,
    AWAITING_EDIT_COURSE_THUMBNAIL,
    AWAITING_EDIT_COURSE_CATEGORY_CHOICE,
    AWAITING_EDIT_COURSE_CONFIRMATION,


    ADMIN_BROADCAST_CHOOSE_TYPE,
    ADMIN_BROADCAST_AWAITING_TEXT,
    ADMIN_BROADCAST_AWAITING_PHOTO,
    ADMIN_BROADCAST_AWAITING_TARGETS,

    AWAITING_EDIT_MODULE_TITLE,
    AWAITING_EDIT_MODULE_DESCRIPTION,
    AWAITING_EDIT_MODULE_PRICE,
    AWAITING_EDIT_MODULE_CONFIRMATION,

    AWAITING_EDIT_LESSON_TITLE,
    AWAITING_EDIT_LESSON_DESCRIPTION,
    AWAITING_EDIT_LESSON_IS_FREE,
    AWAITING_EDIT_LESSON_CONFIRMATION;




}
